baseURL = 'https://example.org/'
languageCode = 'it-IT'
title = 'Hotel Moderno Demonte'

defaultContentLanguage = "it"
defaultContentLanguageInSubdir = true

[languages.it]
languageName = "Italiano"
weight = 1
contentDir = "content/it"

[languages.en]
languageName = "English"
weight = 2
contentDir = "content/en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Hotel accogliente a Demonte nel cuore della Valle Stura provincia di Cuneo. Camere confortevoli, ristorante tipico e relax in montagna."   
